"use client";

import { Pencil, Plus, Save, Trash2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { Money } from "@/components/Money";
import { useFetchData } from "@/components/panel/useFetchData";

type Work = { id: string; name: string };
type Tag = { id: string; name: string; color: string; active: boolean };
type ReasonAction = "REPROVAR" | "TRANSFERIR" | "CANCELAR" | "SOLICITAR_INFO" | "REABRIR";
type Reason = { id: string; action: ReasonAction; label: string; active: boolean; sortOrder: number };
type ApprovalRule = { id: string; name: string; minAmount: number; maxAmount: number | null; workId: string | null; category: string | null; tagId: string | null; requiredRole: "GESTOR" | "COORDENADOR"; requiredApprovals: number; preventSelfApproval: boolean; priority: number; active: boolean; work?: Work | null; tag?: Tag | null };
type Config = { works: Work[]; tags: Tag[]; reasons: Reason[]; approvalRules: ApprovalRule[] };
const emptyApproval = { id: "", name: "", minAmount: "0", maxAmount: "", workId: "", category: "", tagId: "", requiredRole: "GESTOR" as "GESTOR" | "COORDENADOR", requiredApprovals: "1", preventSelfApproval: true, priority: "0", active: true };
const emptyTag = { id: "", name: "", color: "#3157A4", active: true };
const emptyReason = { id: "", reasonAction: "REPROVAR" as ReasonAction, label: "", sortOrder: "0", active: true };
const reasonLabels: Record<ReasonAction, string> = { REPROVAR: "Reprovação", TRANSFERIR: "Remarcação", CANCELAR: "Cancelamento", SOLICITAR_INFO: "Solicitação de informação", REABRIR: "Reabertura" };

export function FinanceConfigTab() {
  const { data, error, loading, reload, setError } = useFetchData<Config>("/api/admin/finance-config");
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [approval, setApproval] = useState(emptyApproval); const [tag, setTag] = useState(emptyTag);
  const [reason, setReason] = useState(emptyReason);

  async function send(body: Record<string, unknown>) {
    setBusy(true); setError(""); setMessage("");
    try { const response = await fetch("/api/admin/finance-config", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "Não foi possível salvar a configuração."); return false; } setMessage(body.action === "delete" ? "Configuração excluída." : "Configuração salva."); reload(); return true; }
    catch { setError("Falha de conexão ao salvar a configuração."); return false; } finally { setBusy(false); }
  }
  async function remove(resource: string, id: string) { if (confirm("Excluir esta configuração?")) await send({ resource, action: "delete", id }); }
  async function saveApproval(e: FormEvent) { e.preventDefault(); if (await send({ resource: "approval_rule", action: "save", ...approval, id: approval.id || undefined, minAmount: Number(approval.minAmount), maxAmount: approval.maxAmount ? Number(approval.maxAmount) : null, workId: approval.workId || null, category: approval.category || null, tagId: approval.tagId || null, requiredApprovals: Number(approval.requiredApprovals), priority: Number(approval.priority) })) setApproval(emptyApproval); }
  async function saveTag(e: FormEvent) { e.preventDefault(); if (await send({ resource: "tag", action: "save", ...tag, id: tag.id || undefined })) setTag(emptyTag); }
  async function saveReason(e: FormEvent) { e.preventDefault(); if (await send({ resource: "reason", action: "save", ...reason, id: reason.id || undefined, sortOrder: Number(reason.sortOrder) })) setReason(emptyReason); }

  if (loading || !data) return <div className="panel pad">Carregando configurações financeiras...</div>;
  return <>
    {error ? <div className="alert error">{error}</div> : null}{message ? <div className="alert success">{message}</div> : null}

    <section className="panel pad form-grid"><div className="section-header"><div><h2>Alçadas de aprovação</h2><span className="muted">A regra de maior prioridade que combinar com o pagamento será aplicada.</span></div></div>
      <form className="form-grid two" onSubmit={saveApproval}><div className="field span-2"><label>Nome da regra</label><input className="input" value={approval.name} onChange={(e) => setApproval({ ...approval, name: e.target.value })} required /></div><div className="field"><label>Valor mínimo</label><input className="input" type="number" min="0" step="0.01" value={approval.minAmount} onChange={(e) => setApproval({ ...approval, minAmount: e.target.value })} /></div><div className="field"><label>Valor máximo (vazio = sem limite)</label><input className="input" type="number" min="0" step="0.01" value={approval.maxAmount} onChange={(e) => setApproval({ ...approval, maxAmount: e.target.value })} /></div><div className="field"><label>Obra (opcional)</label><select className="select" value={approval.workId} onChange={(e) => setApproval({ ...approval, workId: e.target.value })}><option value="">Todas</option>{data.works.map((work) => <option key={work.id} value={work.id}>{work.name}</option>)}</select></div><div className="field"><label>Categoria (opcional)</label><input className="input" value={approval.category} onChange={(e) => setApproval({ ...approval, category: e.target.value })} /></div><div className="field"><label>Tag (opcional)</label><select className="select" value={approval.tagId} onChange={(e) => setApproval({ ...approval, tagId: e.target.value })}><option value="">Qualquer tag</option>{data.tags.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="field"><label>Perfil mínimo</label><select className="select" value={approval.requiredRole} onChange={(e) => setApproval({ ...approval, requiredRole: e.target.value as "GESTOR" | "COORDENADOR" })}><option value="GESTOR">Gestor</option><option value="COORDENADOR">Coordenador</option></select></div><div className="field"><label>Quantidade de aprovadores</label><input className="input" type="number" min="1" max="5" value={approval.requiredApprovals} onChange={(e) => setApproval({ ...approval, requiredApprovals: e.target.value })} /></div><div className="field"><label>Prioridade</label><input className="input" type="number" min="0" value={approval.priority} onChange={(e) => setApproval({ ...approval, priority: e.target.value })} /></div><label className="check-row"><input type="checkbox" checked={approval.preventSelfApproval} onChange={(e) => setApproval({ ...approval, preventSelfApproval: e.target.checked })} /> Impedir autoaprovação</label><label className="check-row"><input type="checkbox" checked={approval.active} onChange={(e) => setApproval({ ...approval, active: e.target.checked })} /> Regra ativa</label><div className="button-row span-2"><button className="button" disabled={busy}><Save size={16} /> Salvar alçada</button>{approval.id ? <button className="button secondary" type="button" onClick={() => setApproval(emptyApproval)}>Cancelar edição</button> : null}</div></form>
      <div className="table-wrap"><table className="table"><thead><tr><th>Regra</th><th>Faixa</th><th>Filtro</th><th>Exigência</th><th /></tr></thead><tbody>{data.approvalRules.map((item) => <tr key={item.id}><td><strong>{item.name}</strong><small className="muted">Prioridade {item.priority} · {item.active ? "ativa" : "inativa"}</small></td><td><Money value={item.minAmount} /> até {item.maxAmount === null ? "sem limite" : <Money value={item.maxAmount} />}</td><td>{item.work?.name ?? "Todas as obras"}<small className="muted">{item.category || item.tag?.name || "Todas as categorias/tags"}</small></td><td>{item.requiredApprovals} × {item.requiredRole === "COORDENADOR" ? "Coordenador" : "Gestor"}<small className="muted">{item.preventSelfApproval ? "Sem autoaprovação" : "Autoaprovação permitida"}</small></td><td><div className="button-row"><button className="icon-button" type="button" onClick={() => setApproval({ id: item.id, name: item.name, minAmount: String(item.minAmount), maxAmount: item.maxAmount === null ? "" : String(item.maxAmount), workId: item.workId ?? "", category: item.category ?? "", tagId: item.tagId ?? "", requiredRole: item.requiredRole, requiredApprovals: String(item.requiredApprovals), preventSelfApproval: item.preventSelfApproval, priority: String(item.priority), active: item.active })}><Pencil size={15} /></button><button className="icon-button" type="button" onClick={() => void remove("approval_rule", item.id)}><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div>
    </section>

    <section className="split-grid"><div className="panel pad form-grid"><h2>Tags personalizadas</h2><form className="toolbar" onSubmit={saveTag}><input className="input" placeholder="Nome da tag" value={tag.name} onChange={(e) => setTag({ ...tag, name: e.target.value })} required /><input className="input color-input" type="color" value={tag.color} onChange={(e) => setTag({ ...tag, color: e.target.value })} /><button className="button"><Plus size={16} /> Salvar</button></form><div className="tag-list">{data.tags.map((item) => <span className="tag-chip" style={{ borderColor: item.color }} key={item.id}><i style={{ background: item.color }} />{item.name}<button type="button" onClick={() => setTag({ id: item.id, name: item.name, color: item.color, active: item.active })}><Pencil size={12} /></button><button type="button" onClick={() => void remove("tag", item.id)}><Trash2 size={12} /></button></span>)}</div></div>
      <div className="panel pad form-grid"><h2>Motivos padronizados</h2><form className="form-grid" onSubmit={saveReason}><select className="select" value={reason.reasonAction} onChange={(e) => setReason({ ...reason, reasonAction: e.target.value as ReasonAction })}>{Object.entries(reasonLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><input className="input" placeholder="Motivo" value={reason.label} onChange={(e) => setReason({ ...reason, label: e.target.value })} required /><button className="button"><Save size={16} /> Salvar motivo</button></form><div className="detail-list">{data.reasons.map((item) => <div className="detail-item" key={item.id}><span>{reasonLabels[item.action]}</span><strong>{item.label}</strong><div className="button-row"><button className="icon-button" type="button" onClick={() => setReason({ id: item.id, reasonAction: item.action, label: item.label, sortOrder: String(item.sortOrder), active: item.active })}><Pencil size={14} /></button><button className="icon-button" type="button" onClick={() => void remove("reason", item.id)}><Trash2 size={14} /></button></div></div>)}</div></div></section>

  </>;
}
